### ISSUE TITLE
Add pg-import

### ISSUE THREAD

**Issue by boriscosic** [tesera/pgexport-awslambda#3]
Leverage pg-native to allow this script to import CSVs into tables.

**Comment by zmpeg** [comment]
Progress so far: Successfully open a s3 object as a stream, successfully read the header line and trigger a create table to the specified pgurl.

Todo: Point the stream to the pg instance.

**Comment by zmpeg** [comment]
This import is workign correctly.. Ready for review and merge.

**Comment by boriscosic** [comment]
Can you please add optional support for mappings:
```
mappings: [
    field1: { type: "numeric" },
    field2: { type: "geometry" }
]
````

In this case, field1 would get created as type numeric and field2 as type geometry.

Please update README as well, on how to use pgImport.

**Comment by zmpeg** [comment]
to be clear, numeric might be DECIMAL(6,2) or INTEGER?

**Comment by boriscosic** [comment]
Yes, and maybe a default? All should be optional. 
```
mappings: [
    field1: { type: "numeric" , default: 0 },
    field2: { type: "geometry" , default: null }
]
```

**Comment by zmpeg** [comment]
Also I will change it to skip if the table is already created. Another option here could be to truncate.

**Comment by boriscosic** [comment]
Presumed functionality should be to skip table. Truncate and drop table are fast operations that can be performed client side. This tool should serve a minimal purpose.

**Comment by zmpeg** [comment]
Added 2 more changes, skip tables that exist and allow for data type overrides.

**Comment by zmpeg** [comment]
Added a Usage section for import, similar to export.

**Comment by zmpeg** [comment]
Changed `overrides` to `mappings`. Changed the mapping from a string to an object with a type.

**Comment by zmpeg** [comment]
Merged feature/3-import-csv
